catalog/controller/extension/payment/razorpay.php
catalog/controller/payment/razorpay.php
catalog/view/theme/default/template/payment/razorpay.tpl

Added callback url support for opencart 2.3

Callback url support

---

system/library/razorpay/razorpay-lib/createwebhook.php

Autowebhook pagination

---

catalog/controller/extension/payment/razorpay.php

creates a new razorpay order if cart amount mismatches

added cart amount validation

---

catalog/controller/extension/payment/razorpay.php
install.xml

version changed

---

admin/controller/extension/payment/razorpay.php
admin/view/template/extension/payment/razorpay.twig
catalog/controller/extension/payment/razorpay.php

Webhook add delay

---

catalog/controller/extension/payment/razorpay.php
install.xml

version bump 5.1.1

---

admin/controller/payment/razorpay.php
admin/model/payment/razorpay.php
admin/view/template/payment/razorpay_subscription/razorpay_plan_form.twig

Add new plan form

---

admin/controller/payment/razorpay.php
admin/view/template/payment/razorpay_subscription/razorpay_plan_list.twig

view list of plans

---

catalog/controller/payment/razorpay.php
catalog/model/payment/razorpay.php
catalog/view/template/payment/razorpay.twig

place subscription order

---

admin/controller/payment/razorpay.php
admin/model/payment/razorpay.php
admin/view/template/payment/razorpay_subscription/razorpay_subscription.twig
admin/view/template/payment/razorpay_subscription/razorpay_subscription_info.twig
admin/view/template/payment/razorpay_subscription/razorpay_subscription_list.twig

Oc4 subscription admin

---

catalog/controller/payment/razorpay.php

removed unused updateOCRecurringStatus()

---

admin/controller/payment/razorpay.php
catalog/controller/payment/razorpay.php
install.json

version bump 6.0.1

---

catalog/controller/extension/payment/razorpay.php

Blocked KWD|OMR|BHD currencies

---

catalog/controller/extension/payment/razorpay.php
install.xml

version bump 5.1.2

---

catalog/controller/payment/razorpay.php

added order data mismatch check

---

catalog/controller/payment/razorpay.php
install.json

version bump 6.0.2

---

catalog/controller/extension/payment/razorpay.php

add session in header

---

catalog/controller/extension/payment/razorpay.php
install.xml

version bump 5.1.3

---

catalog/language/en-gb/extension/payment/razorpay.php

PO-32 : removed html and icon

---

catalog/model/extension/payment/razorpay.php

P0-32 : payment method name based on country code

---

catalog/controller/extension/payment/razorpay.php
install.xml

P0-32 : version bump 5.1.4

---

admin/controller/extension/payment/razorpay.php
admin/model/extension/payment/razorpay.php

PLUG-2393 : fixed displaying duplicate plan

---

admin/view/template/payment/razorpay.twig

PLUG-2393 display alert on save config

---

admin/model/payment/razorpay.php

PLUG-2393 fixed displaying duplicate plan

---

admin/controller/payment/razorpay.php
system/library/razorpay/razorpay-lib/createwebhook.php

PLUG-2393 removed alert and adding as log info

---

catalog/controller/payment/razorpay.php
install.json

PLUG-2393 version bump 6.0.3

---

catalog/controller/extension/payment/razorpay.php
install.xml

PLUG-2393 version bump 5.1.5

---

admin/model/extension/payment/razorpay.php
catalog/controller/extension/payment/razorpay.php
catalog/model/extension/payment/razorpay.php

Webhook cron

---

README.md
catalog/controller/extension/payment/razorpay.php
install.xml

version bump 5.1.6

---

admin/controller/extension/payment/razorpay.php
admin/language/en-gb/extension/payment/razorpay.php
admin/view/template/extension/payment/razorpay.twig

PO-94 added cron creation steps in config

---

README.md
catalog/controller/extension/payment/razorpay.php
install.xml

PO-94 version bump 5.1.7

---

catalog/controller/extension/payment/razorpay.php
install.xml

PO-120 version bump 5.1.8

---

admin/controller/payment/razorpay.php
catalog/controller/payment/razorpay.php

PO-293 support version 4.1.0.0
